services:
  backend:
    build: .
    #Add this line for Mac/OS M1/M2 Chips
    #platform: linux/amd64
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SECURITY_JWT_SECRET_KEY=algumasecretkeysegura
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build: ./ui/products-api
    platform: linux/amd64

    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: oscarfonts/h2
    ports:
      - "8090:8082"
    environment:
      - H2_OPTIONS=-browser
    networks:
      - app-network

networks:
  app-network:
    driver: bridge